# Generated by Django 2.0.6 on 2018-06-14 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_state', models.CharField(choices=[('rs', 'registration successful'), ('ru', 'registration unsuccessful')], default='ru', max_length=3)),
                ('class_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searchings.SpecificClass')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('major_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_image', models.ImageField(blank=True, default='profile_image/default.PNG', upload_to='profile_image')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.Student'),
        ),
    ]
