# Generated by Django 2.0.6 on 2018-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_location',
            field=models.CharField(default='', max_length=20),
        ),
    ]
